import React, { Fragment } from 'react'

import { StudiesList } from '../components/studies'
import { SeriesList } from '../components/series'

export const Home: React.FC = () => {
  return (
    <Fragment>
      <h1>Redux + TypeScript</h1>
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier for you. Take a look around ;)
      </p>
      <StudiesList />
      <hr />
      <SeriesList />
    </Fragment>
  )
}
