version: '3.4'

services:
  hb_database:
    image: mongo:latest
    container_name: "hb_database"
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/mongo/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_DB=healthbarbecue
    volumes:
      - ./data/mongo/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

  hb_database_view:
    image: mongo-express:latest
    container_name: "hb_database_view"
    environment:
      - ME_CONFIG_MONGODB_SERVER=hb_database
    links:
      - hb_database
    ports:
      - 8043:8081

  hb_pacs:
    image: jodogne/orthanc-plugins:latest
    container_name: "hb_pacs"
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - ./data/orthanc:/var/lib/orthanc/db/
      - ./config/orthanc.json:/etc/orthanc/orthanc.json

  hb_web_client:
    container_name: hb_web_client
    build:
      context: ./client/web/
      dockerfile: prod.Dockerfile
    volumes:
      - './client/web:/app'
      - '/app/node_modules'
    ports:
      - 4000:80
    environment:
      - CHOKIDAR_USEPOLLING=true

  # hb_business:
  #   image: hb_business
  #   build: ./business
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - mongodb
  #   links:
  #     - mongodb
  # hb_client:
  #   image: hb_client
  #   build: ./client
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3001:3001