version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/mongo/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_DB=healthbarbecue
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

  hb_business:
    image: hb_business
    build: ./business
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    links:
      - mongodb
  hb_client:
    image: hb_client
    build: ./client
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001