version: '3.2'

services:
  hb_database:
    image: mongo:latest
    container_name: "hb_database"
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/mongo/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=healthbarbecue
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
    expose:
      - 27017

  hb_pacs_server:
    image: jodogne/orthanc-plugins:latest
    container_name: hb_pacs_server
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - orthancdata:/var/lib/orthanc/db/
      - ./config/orthanc.json:/etc/orthanc/orthanc.json
    expose:
      - 8042

  hb_business_server:
    container_name: hb_business_server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:4001
      - MongoConfiguration__Servername=hb_database
      - PacsConfiguration__Host=hb_pacs_server
      - AlgoConfiguration__Host=hb_algo_server
    build:
      context: ./business/MetadataDatabase
    ports:
      - 4001:80
    volumes:
      - algoVolume:/app/workspace/
    expose:
      - 4001
    depends_on:
      - hb_database
      - hb_algo_server

  hb_web_server:
    container_name: hb_web_server
    restart: always
    build:
      context: .
      dockerfile: server.Dockerfile
    volumes:
      - './client/web:/app'
      - '/app/node_modules'
    ports:
      - 4000:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - hb_business_server
      - hb_pacs_server

  # End to End test
  hb_end_to_end_test:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    build:
      context: ./end-to-end-tests
      dockerfile: Dockerfile
    container_name: hb_end_to_end_test
    links:
      - hb_web_server
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://hb_web_server
      - dbUrl=mongodb://hb_database
    volumes:
      - ./end-to-end-tests:/app

  hb_algo_server:
    container_name: hb_algo_server
    build:
      context: ./business/Algo
    volumes:
      - algoVolume:/usr/src/app/workspace
    ports:
      - 5009:5009
    expose:
      - 5009

volumes:
  mongodata: {}
  orthancdata: {}
  algoVolume: {}
