version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0
  windows: circleci/windows@2.2.0
executors:
  node-executor:
    docker:
      - image: circleci/node:13.12.0
  with-chrome:
    docker:
      - image: 'cypress/browsers:chrome69'
jobs:
  # Run all tests related to the web client
  test-webclient:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Tests for Web Client
          command: |
            cd client/web
            yarn install --silent
            # Run unit tests
            yarn test
            
            ## lint [Seems to be long to run. Should we keep it on every build?]
            # yarn lint
            
            # Build production web client
            yarn build
  unit-tests-business:
    executor:
      name: windows/default
    steps:
      - checkout
      - run: dotnet test business\tests\UnitTests.csproj
  end-to-end-tests:
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker-compose up --exit-code-from hb_end_to_end_test

workflows:
  build:
    jobs:
      #- test-webclient
      #- unit-tests-business
      - end-to-end-tests
      # - cypress/install:
      #     name: 'Start web client'
      #     working_directory: end-to-end-tests
      #     build: |
      #       pwd
      #       ls
      #       cd client/web
      #       yarn
      #       yarn add -D cross-env
      #       yarn build
      #       ls
      #       cd build 
      #       pwd 
      #       echo "Will start web client: yarn start"
      #     cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "end-to-end-tests/package.json" }}'
      #     post-steps:
      #       - run:
      #           name: 'Run client web'
      #           command: echo "Could have done something here"
      #             #cd build && yarn && yarn start &
      #           background: true
      # - cypress/run:
      #     executor: with-chrome
      #     requires: 
      #       - Start web client
      #     yarn: true
      #     working_directory: end-to-end-tests
      #     start: |
      #       pwd
      #       ls
      #       cd ..
      #       pwd
      #       ls
      #       cd client/web/
      #       pwd
      #       ls
      #       yarn global add serve
      #       echo "Will start web client yarn start"
      #       serve -s build
      #       echo "Server is supposed to be started. Cyril"
      #     wait-on: 'http://localhost:5000'
      #     cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "end-to-end-tests/package.json" }}'