version: 2
jobs:
  build-docker:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run: 
          name: Build Health Barbecue docker-compose
          command: |
            pwd
#            docker-compose -f "docker-compose.yml" up -d --build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-docker
