<<<<<<< HEAD
version: 2.1

orbs:
  windows: circleci/windows@2.2.0

executors:
  node-executor:
    docker:
      - image: circleci/node:13.12.0

jobs:
  # Run all tests related to the web client
  test-webclient:
    executor: node-executor
=======
version: 2
jobs:
  # Run all tests related to the web client
  test-webclient:
    docker:
      - image: circleci/node:13.12.0
>>>>>>> Revert "Try to run test on ci."
    steps:
      - checkout
      - run:
          name: Tests for Web Client
          command: |
            cd client/web
            yarn install --silent
            # Run unit tests
            yarn test
            
            ## lint [Seems to be long to run. Should we keep it on every build?]
            # yarn lint
            
            # Build production web client
            yarn build
<<<<<<< HEAD
  unit-tests-business:
    executor:
      name: windows/default
    steps:
      - checkout
      - run: dotnet test business\tests\UnitTests.csproj
=======
>>>>>>> Revert "Try to run test on ci."
    
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-webclient
<<<<<<< HEAD
      - unit-tests-business
=======
>>>>>>> Revert "Try to run test on ci."
