version: 2
jobs:
  # Run all tests related to the web client
  test-webclient:
    docker:
      - image: circleci/node:13.12.0
    steps:
      - checkout
      - run:
          name: Tests for Web Client
          command: |
            cd client/web
            yarn install --silent
            yarn global add react-scripts --silent
            # Run unit tests
            yarn test
            
            ## lint [Seems to be long to run. Should we keep it on every build?]
            # yarn lint
            
            # Build production web client
            yarn build
    
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-webclient
