export const SET_CURRENT_SERIE = 'SET_CURRENT_SERIE'
export const UNSET_CURRENT_SERIE = 'UNSET_CURRENT_SERIE'
export const SET_ALL_SERIES = 'SET_ALL_SERIES'
export const FETCH_ALL_SERIES = 'FETCH_ALL_SERIES'
