export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER'
export const SET_ALL_USERS = 'SET_ALL_USERS'
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'

export const SAVE_ONE_USER = 'SAVE_ONE_USER'
export const SET_USER_FORM_RESULT = 'SET_USER_FORM_RESULT'
export const RESET_USER_FORM_RESULT = 'RESET_USER_FORM_RESULT'
